version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cashback}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cashback}
      POSTGRES_DB: ${POSTGRES_DB:-cashback}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ../apps/api
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure-secret}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      POSTGRES_DB: ${POSTGRES_DB:-cashback}
      POSTGRES_USER: ${POSTGRES_USER:-cashback}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cashback}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
      LOAD_SEEDS: ${LOAD_SEEDS:-true}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "python src/manage.py migrate && if [ \"$${LOAD_SEEDS}\" = \"true\" ]; then python src/manage.py runseeds; fi && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../apps/api:/app
    working_dir: /app

  web:
    build: ../apps/web
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports:
      - "5173:5173"
    volumes:
      - ../apps/web:/app
    working_dir: /app
    command: sh -c "npm ci || npm install && npm run dev -- --host"

volumes:
  db_data:
